#!/bin/bash

# Key and N value generated by my C code
key=254791
n=255811

echo value,time > out.csv

t=1
while [ $t -le 2048 ]; do
	val=""
        i=1
        while [ $i -le 512 ]; do
		val=$val$(($RANDOM%10))
                let i=i+1
	done
	time=`/data/local/tmp/rsac $key $n $val`

	echo $val,$time	>> out.csv
        echo "\rSamples Complete: $t"
        let t=t+1
done

