#!/bin/bash

# Key and N value generated by my C code
key=254791
n=255811

echo value,time > out.csv

for t in {1..2048}
do
	val=""

	for i in {1..512}
	do
		val=$val$(($RANDOM%10))
	done

	time=`./rsac $key $n $val`
	
	echo $val,$time	>> out.csv
	printf "\rSamples Complete: $t"
done
